// GENERATED by fushi/tool/icons/gen_fushi_symbols.py — 不要手改，改 SYMBOLS 表后重跑。
// Material Symbols Rounded @ google/material-design-icons 737e3324305806514d7909874fa1818ae1808232
part of 'fushi_icons.dart';

/// 语义图标表（线框 / FILL=0）。选中态用 [FushiIcons.filled]。
abstract final class FushiIcons {
  /// 首页：Symbols `home`（取代 Icons.home_outlined / Icons.home）
  static const IconData home = IconData(
    0xe9b2,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 书 / 书架：Symbols `menu_book`（取代 Icons.menu_book_outlined / Icons.menu_book）
  static const IconData books = IconData(
    0xea19,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 漫画：Symbols `photo_library`（取代 Icons.photo_library_outlined / Icons.photo_library）
  static const IconData manga = IconData(
    0xe413,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 视频：Symbols `movie`（取代 Icons.movie_outlined / Icons.movie）
  static const IconData video = IconData(
    0xe404,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 浏览（来源 / 扩展 / 发现）：Symbols `explore`（取代 Icons.explore_outlined / Icons.explore）
  static const IconData browse = IconData(
    0xe87a,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 查词 / 搜索：Symbols `search`（取代 Icons.search / Icons.search）
  static const IconData lookup = IconData(
    0xef7a,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 游戏：Symbols `sports_esports`（取代 Icons.sports_esports_outlined / Icons.sports_esports）
  static const IconData games = IconData(
    0xea28,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 浏览器扩展 / 插件：Symbols `extension`（取代 Icons.extension_outlined / Icons.extension）
  static const IconData browserExtension = IconData(
    0xe87b,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 设置（导航与入口）：Symbols `tune`（取代 Icons.tune_outlined / Icons.tune）
  static const IconData settings = IconData(
    0xe429,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 齿轮设置（子页内的配置项）：Symbols `settings`（取代 Icons.settings_outlined / Icons.settings）
  static const IconData settingsGear = IconData(
    0xe8b8,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 有声书 / 听力：Symbols `headphones`（取代 Icons.headphones_outlined / Icons.headphones）
  static const IconData audiobook = IconData(
    0xf01f,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 词典：Symbols `dictionary`（取代 Icons.library_books_outlined / Icons.library_books）
  static const IconData dictionary = IconData(
    0xf539,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 字幕：Symbols `subtitles`（取代 Icons.subtitles_outlined / Icons.subtitles）
  static const IconData subtitles = IconData(
    0xe048,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 合集：Symbols `collections_bookmark`（取代 Icons.collections_bookmark_outlined / Icons.collections_bookmark）
  static const IconData collection = IconData(
    0xe431,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 标签：Symbols `sell`（取代 Icons.sell_outlined / Icons.sell）
  static const IconData tag = IconData(
    0xf05b,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 统计：Symbols `insights`（取代 Icons.insights_outlined / Icons.insights）
  static const IconData statistics = IconData(
    0xf092,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 制卡 / Anki：Symbols `style`（取代 Icons.style_outlined / Icons.style）
  static const IconData ankiCard = IconData(
    0xe41d,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// OCR / 识别：Symbols `document_scanner`（取代 Icons.document_scanner_outlined / Icons.document_scanner）
  static const IconData ocr = IconData(
    0xe5fa,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 歌词模式：Symbols `lyrics`（取代 Icons.lyrics_outlined / Icons.lyrics）
  static const IconData lyrics = IconData(
    0xec0b,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 游戏条目：Symbols `videogame_asset`（取代 Icons.videogame_asset_outlined / Icons.videogame_asset）
  static const IconData game = IconData(
    0xe338,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 电视 / 番剧：Symbols `live_tv`（取代 Icons.live_tv_outlined / Icons.live_tv）
  static const IconData tv = IconData(
    0xe63a,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 返回：Symbols `arrow_back`（取代 Icons.arrow_back / Icons.arrow_back）
  static const IconData back = IconData(
    0xe5c4,
    fontFamily: kFushiSymbolsFontFamily,
    matchTextDirection: true,
  );

  /// 前进：Symbols `arrow_forward`（取代 Icons.arrow_forward / Icons.arrow_forward）
  static const IconData forward = IconData(
    0xe5c8,
    fontFamily: kFushiSymbolsFontFamily,
    matchTextDirection: true,
  );

  /// 关闭：Symbols `close`（取代 Icons.close / Icons.close）
  static const IconData close = IconData(
    0xe5cd,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 更多（竖）：Symbols `more_vert`（取代 Icons.more_vert / Icons.more_vert）
  static const IconData more = IconData(
    0xe5d4,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 更多（横）：Symbols `more_horiz`（取代 Icons.more_horiz / Icons.more_horiz）
  static const IconData moreHoriz = IconData(
    0xe5d3,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 菜单：Symbols `menu`（取代 Icons.menu / Icons.menu）
  static const IconData menu = IconData(
    0xe5d2,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 新增：Symbols `add`（取代 Icons.add / Icons.add）
  static const IconData add = IconData(
    0xe145,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 新增（圆）：Symbols `add_circle`（取代 Icons.add_circle_outline / Icons.add_circle）
  static const IconData addCircle = IconData(
    0xe990,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 编辑：Symbols `edit`（取代 Icons.edit_outlined / Icons.edit）
  static const IconData edit = IconData(
    0xf097,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 重命名：Symbols `drive_file_rename_outline`（取代 Icons.drive_file_rename_outline / Icons.drive_file_rename_outline）
  static const IconData rename = IconData(
    0xe9a2,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 删除：Symbols `delete`（取代 Icons.delete_outline / Icons.delete）
  static const IconData delete = IconData(
    0xe92e,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 批量清理：Symbols `delete_sweep`（取代 Icons.delete_sweep_outlined / Icons.delete_sweep）
  static const IconData deleteSweep = IconData(
    0xe16c,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 刷新：Symbols `refresh`（取代 Icons.refresh / Icons.refresh）
  static const IconData refresh = IconData(
    0xe5d5,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 重置 / 恢复默认：Symbols `restart_alt`（取代 Icons.restart_alt / Icons.restart_alt）
  static const IconData restart = IconData(
    0xf053,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 撤销：Symbols `undo`（取代 Icons.undo / Icons.undo）
  static const IconData undo = IconData(
    0xe166,
    fontFamily: kFushiSymbolsFontFamily,
    matchTextDirection: true,
  );

  /// 重做：Symbols `redo`（取代 Icons.redo / Icons.redo）
  static const IconData redo = IconData(
    0xe15a,
    fontFamily: kFushiSymbolsFontFamily,
    matchTextDirection: true,
  );

  /// 保存：Symbols `save`（取代 Icons.save_outlined / Icons.save）
  static const IconData save = IconData(
    0xe161,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 搜索：Symbols `search`（取代 Icons.search / Icons.search）
  static const IconData search = IconData(
    0xef7a,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 高级搜索 / 检索设置：Symbols `manage_search`（取代 Icons.manage_search / Icons.manage_search）
  static const IconData manageSearch = IconData(
    0xf02f,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 筛选：Symbols `filter_alt`（取代 Icons.filter_alt_outlined / Icons.filter_alt）
  static const IconData filter = IconData(
    0xef4f,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 筛选列表：Symbols `filter_list`（取代 Icons.filter_list / Icons.filter_list）
  static const IconData filterList = IconData(
    0xe152,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 排序：Symbols `sort`（取代 Icons.sort / Icons.sort）
  static const IconData sort = IconData(
    0xe164,
    fontFamily: kFushiSymbolsFontFamily,
    matchTextDirection: true,
  );

  /// 分享：Symbols `share`（取代 Icons.share_outlined / Icons.share）
  static const IconData share = IconData(
    0xe80d,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 外部打开：Symbols `open_in_new`（取代 Icons.open_in_new / Icons.open_in_new）
  static const IconData openInNew = IconData(
    0xe89e,
    fontFamily: kFushiSymbolsFontFamily,
    matchTextDirection: true,
  );

  /// 下载：Symbols `download`（取代 Icons.download_outlined / Icons.download）
  static const IconData download = IconData(
    0xf090,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 上传：Symbols `upload`（取代 Icons.upload_outlined / Icons.upload）
  static const IconData upload = IconData(
    0xf09b,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 导入文件：Symbols `upload_file`（取代 Icons.upload_file_outlined / Icons.upload_file）
  static const IconData importFile = IconData(
    0xe9fc,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 同步：Symbols `sync`（取代 Icons.sync / Icons.sync）
  static const IconData sync = IconData(
    0xe627,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 云同步：Symbols `cloud_sync`（取代 Icons.cloud_sync_outlined / Icons.cloud_sync）
  static const IconData cloudSync = IconData(
    0xeb5a,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 复制：Symbols `content_copy`（取代 Icons.content_copy_outlined / Icons.content_copy）
  static const IconData copy = IconData(
    0xe14d,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 链接：Symbols `link`（取代 Icons.link / Icons.link）
  static const IconData link = IconData(
    0xe250,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 取消链接：Symbols `link_off`（取代 Icons.link_off / Icons.link_off）
  static const IconData linkOff = IconData(
    0xe16f,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 置顶 / 固定：Symbols `push_pin`（取代 Icons.push_pin_outlined / Icons.push_pin）
  static const IconData pin = IconData(
    0xf10d,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 书签：Symbols `bookmark`（取代 Icons.bookmark_outline / Icons.bookmark）
  static const IconData bookmark = IconData(
    0xe8e7,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 加书签：Symbols `bookmark_add`（取代 Icons.bookmark_add_outlined / Icons.bookmark_add）
  static const IconData bookmarkAdd = IconData(
    0xe598,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 收藏：Symbols `favorite`（取代 Icons.favorite_border / Icons.favorite）
  static const IconData favorite = IconData(
    0xe87e,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 星标 / 评分：Symbols `star`（取代 Icons.star_border / Icons.star）
  static const IconData star = IconData(
    0xf09a,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 历史：Symbols `history`（取代 Icons.history / Icons.history）
  static const IconData history = IconData(
    0xe8b3,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 时间 / 计划：Symbols `schedule`（取代 Icons.schedule / Icons.schedule）
  static const IconData schedule = IconData(
    0xefd6,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 日历：Symbols `calendar_month`（取代 Icons.calendar_month_outlined / Icons.calendar_month）
  static const IconData calendar = IconData(
    0xebcc,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 计时：Symbols `timer`（取代 Icons.timer_outlined / Icons.timer）
  static const IconData timer = IconData(
    0xe425,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 速度：Symbols `speed`（取代 Icons.speed / Icons.speed）
  static const IconData speed = IconData(
    0xe9e4,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 加入库：Symbols `library_add`（取代 Icons.library_add_outlined / Icons.library_add）
  static const IconData libraryAdd = IconData(
    0xe03c,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 拖动手柄：Symbols `drag_handle`（取代 Icons.drag_handle / Icons.drag_handle）
  static const IconData dragHandle = IconData(
    0xe25d,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 全选：Symbols `select_all`（取代 Icons.select_all / Icons.select_all）
  static const IconData selectAll = IconData(
    0xe162,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 多选 / 清单：Symbols `checklist`（取代 Icons.checklist / Icons.checklist）
  static const IconData checklist = IconData(
    0xe6b1,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 切换 / 交换：Symbols `swap_horiz`（取代 Icons.swap_horiz / Icons.swap_horiz）
  static const IconData swap = IconData(
    0xe8d4,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 放大：Symbols `zoom_in`（取代 Icons.zoom_in / Icons.zoom_in）
  static const IconData zoomIn = IconData(
    0xe8ff,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 缩小：Symbols `zoom_out`（取代 Icons.zoom_out / Icons.zoom_out）
  static const IconData zoomOut = IconData(
    0xe900,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 全屏：Symbols `fullscreen`（取代 Icons.fullscreen / Icons.fullscreen）
  static const IconData fullscreen = IconData(
    0xe5d0,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 退出全屏：Symbols `fullscreen_exit`（取代 Icons.fullscreen_exit / Icons.fullscreen_exit）
  static const IconData fullscreenExit = IconData(
    0xe5d1,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 网格视图：Symbols `grid_view`（取代 Icons.grid_view_outlined / Icons.grid_view）
  static const IconData gridView = IconData(
    0xe9b0,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 列表视图：Symbols `view_list`（取代 Icons.view_list_outlined / Icons.view_list）
  static const IconData listView = IconData(
    0xe8ef,
    fontFamily: kFushiSymbolsFontFamily,
    matchTextDirection: true,
  );

  /// 显示：Symbols `visibility`（取代 Icons.visibility_outlined / Icons.visibility）
  static const IconData visibility = IconData(
    0xe8f4,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 隐藏：Symbols `visibility_off`（取代 Icons.visibility_off_outlined / Icons.visibility_off）
  static const IconData visibilityOff = IconData(
    0xe8f5,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 锁定：Symbols `lock`（取代 Icons.lock_outline / Icons.lock）
  static const IconData lock = IconData(
    0xe899,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 解锁：Symbols `lock_open`（取代 Icons.lock_open_outlined / Icons.lock_open）
  static const IconData lockOpen = IconData(
    0xe898,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 进入（右箭头）：Symbols `chevron_right`（取代 Icons.chevron_right / Icons.chevron_right）
  static const IconData chevronRight = IconData(
    0xe5cc,
    fontFamily: kFushiSymbolsFontFamily,
    matchTextDirection: true,
  );

  /// 左箭头：Symbols `chevron_left`（取代 Icons.chevron_left / Icons.chevron_left）
  static const IconData chevronLeft = IconData(
    0xe5cb,
    fontFamily: kFushiSymbolsFontFamily,
    matchTextDirection: true,
  );

  /// 展开：Symbols `expand_more`（取代 Icons.expand_more / Icons.expand_more）
  static const IconData expandMore = IconData(
    0xe5cf,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 收起：Symbols `expand_less`（取代 Icons.expand_less / Icons.expand_less）
  static const IconData expandLess = IconData(
    0xe5ce,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 下拉：Symbols `arrow_drop_down`（取代 Icons.arrow_drop_down / Icons.arrow_drop_down）
  static const IconData dropDown = IconData(
    0xe5c5,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 完成 / 勾：Symbols `check`（取代 Icons.check / Icons.check）
  static const IconData check = IconData(
    0xe668,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 成功：Symbols `check_circle`（取代 Icons.check_circle_outline / Icons.check_circle）
  static const IconData success = IconData(
    0xf0be,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 信息：Symbols `info`（取代 Icons.info_outline / Icons.info）
  static const IconData info = IconData(
    0xe88e,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 警告：Symbols `warning`（取代 Icons.warning_amber_outlined / Icons.warning）
  static const IconData warning = IconData(
    0xf083,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 错误：Symbols `error`（取代 Icons.error_outline / Icons.error）
  static const IconData error = IconData(
    0xf8b6,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 帮助：Symbols `help`（取代 Icons.help_outline / Icons.help）
  static const IconData help = IconData(
    0xe8fd,
    fontFamily: kFushiSymbolsFontFamily,
    matchTextDirection: true,
  );

  /// 禁止 / 屏蔽：Symbols `block`（取代 Icons.block / Icons.block）
  static const IconData block = IconData(
    0xf08c,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 等待中：Symbols `hourglass_top`（取代 Icons.hourglass_top / Icons.hourglass_top）
  static const IconData pending = IconData(
    0xea5b,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 下载中：Symbols `downloading`（取代 Icons.downloading / Icons.downloading）
  static const IconData downloading = IconData(
    0xf001,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 已下载：Symbols `download_done`（取代 Icons.download_done / Icons.download_done）
  static const IconData downloadDone = IconData(
    0xf091,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 云端：Symbols `cloud`（取代 Icons.cloud_outlined / Icons.cloud）
  static const IconData cloud = IconData(
    0xf15c,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 离线 / 云端不可用：Symbols `cloud_off`（取代 Icons.cloud_off_outlined / Icons.cloud_off）
  static const IconData cloudOff = IconData(
    0xe2c1,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 云端下载：Symbols `cloud_download`（取代 Icons.cloud_download_outlined / Icons.cloud_download）
  static const IconData cloudDownload = IconData(
    0xe2c0,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 云端上传：Symbols `cloud_upload`（取代 Icons.cloud_upload_outlined / Icons.cloud_upload）
  static const IconData cloudUpload = IconData(
    0xe2c3,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 无搜索结果：Symbols `search_off`（取代 Icons.search_off / Icons.search_off）
  static const IconData searchOff = IconData(
    0xea76,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 图片损坏：Symbols `broken_image`（取代 Icons.broken_image_outlined / Icons.broken_image）
  static const IconData brokenImage = IconData(
    0xe3ad,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 标记：Symbols `flag`（取代 Icons.flag_outlined / Icons.flag）
  static const IconData flag = IconData(
    0xf0c6,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 已验证：Symbols `verified`（取代 Icons.verified_outlined / Icons.verified）
  static const IconData verified = IconData(
    0xef76,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 通知：Symbols `notifications`（取代 Icons.notifications_outlined / Icons.notifications）
  static const IconData notifications = IconData(
    0xe7f5,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 外观 / 配色：Symbols `palette`（取代 Icons.palette_outlined / Icons.palette）
  static const IconData appearance = IconData(
    0xe40a,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 语言 / 翻译：Symbols `translate`（取代 Icons.translate / Icons.translate）
  static const IconData language = IconData(
    0xe8e2,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 网络 / 公开：Symbols `public`（取代 Icons.public / Icons.public）
  static const IconData globe = IconData(
    0xe80b,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 文字：Symbols `text_fields`（取代 Icons.text_fields / Icons.text_fields）
  static const IconData textFields = IconData(
    0xe262,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 字号：Symbols `format_size`（取代 Icons.format_size / Icons.format_size）
  static const IconData fontSize = IconData(
    0xe245,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 字体：Symbols `font_download`（取代 Icons.font_download_outlined / Icons.font_download）
  static const IconData font = IconData(
    0xe167,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 键盘 / 快捷键：Symbols `keyboard`（取代 Icons.keyboard_outlined / Icons.keyboard）
  static const IconData keyboard = IconData(
    0xe312,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 鼠标：Symbols `mouse`（取代 Icons.mouse_outlined / Icons.mouse）
  static const IconData mouse = IconData(
    0xe323,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 触控 / 手势：Symbols `touch_app`（取代 Icons.touch_app_outlined / Icons.touch_app）
  static const IconData touch = IconData(
    0xe913,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 设备 / 互联：Symbols `devices`（取代 Icons.devices_outlined / Icons.devices）
  static const IconData devices = IconData(
    0xe326,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 服务器：Symbols `dns`（取代 Icons.dns_outlined / Icons.dns）
  static const IconData server = IconData(
    0xe875,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 互联中枢：Symbols `hub`（取代 Icons.hub_outlined / Icons.hub）
  static const IconData hub = IconData(
    0xe9f4,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 局域网：Symbols `wifi`（取代 Icons.wifi / Icons.wifi）
  static const IconData wifi = IconData(
    0xe63e,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 个人 / 档案：Symbols `person`（取代 Icons.person_outline / Icons.person）
  static const IconData person = IconData(
    0xf0d3,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 账号：Symbols `account_circle`（取代 Icons.account_circle_outlined / Icons.account_circle）
  static const IconData account = IconData(
    0xf20b,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 登录：Symbols `login`（取代 Icons.login / Icons.login）
  static const IconData login = IconData(
    0xea77,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 登出：Symbols `logout`（取代 Icons.logout / Icons.logout）
  static const IconData logout = IconData(
    0xe9ba,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 密钥：Symbols `key`（取代 Icons.key_outlined / Icons.key）
  static const IconData key = IconData(
    0xe73c,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 安全 / 隐私：Symbols `shield`（取代 Icons.shield_outlined / Icons.shield）
  static const IconData shield = IconData(
    0xe9e0,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 存储 / 数据：Symbols `inventory_2`（取代 Icons.inventory_2_outlined / Icons.inventory_2）
  static const IconData storage = IconData(
    0xe1a1,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 备份：Symbols `backup`（取代 Icons.backup_outlined / Icons.backup）
  static const IconData backup = IconData(
    0xe864,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 还原备份：Symbols `settings_backup_restore`（取代 Icons.settings_backup_restore / Icons.settings_backup_restore）
  static const IconData restoreBackup = IconData(
    0xe8ba,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 文件夹：Symbols `folder`（取代 Icons.folder_outlined / Icons.folder）
  static const IconData folder = IconData(
    0xe2c7,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 打开文件夹：Symbols `folder_open`（取代 Icons.folder_open_outlined / Icons.folder_open）
  static const IconData folderOpen = IconData(
    0xe2c8,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 文件 / 文档：Symbols `description`（取代 Icons.description_outlined / Icons.description）
  static const IconData file = IconData(
    0xe873,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 图片：Symbols `image`（取代 Icons.image_outlined / Icons.image）
  static const IconData image = IconData(
    0xe3f4,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 以图搜索：Symbols `image_search`（取代 Icons.image_search_outlined / Icons.image_search）
  static const IconData imageSearch = IconData(
    0xe43f,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 深色：Symbols `dark_mode`（取代 Icons.dark_mode_outlined / Icons.dark_mode）
  static const IconData darkMode = IconData(
    0xe51c,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 浅色：Symbols `light_mode`（取代 Icons.light_mode_outlined / Icons.light_mode）
  static const IconData lightMode = IconData(
    0xe518,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 跟随系统明暗：Symbols `brightness_6`（取代 Icons.brightness_6_outlined / Icons.brightness_6）
  static const IconData brightnessAuto = IconData(
    0xe3ab,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// AI / 智能：Symbols `auto_awesome`（取代 Icons.auto_awesome_outlined / Icons.auto_awesome）
  static const IconData ai = IconData(
    0xe65f,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 柱状图：Symbols `bar_chart`（取代 Icons.bar_chart / Icons.bar_chart）
  static const IconData barChart = IconData(
    0xe26b,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 组件 / 模块：Symbols `widgets`（取代 Icons.widgets_outlined / Icons.widgets）
  static const IconData widgets = IconData(
    0xe1bd,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 自定义面板：Symbols `dashboard_customize`（取代 Icons.dashboard_customize_outlined / Icons.dashboard_customize）
  static const IconData dashboardCustomize = IconData(
    0xe99b,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 引文 / 例句：Symbols `format_quote`（取代 Icons.format_quote / Icons.format_quote）
  static const IconData quote = IconData(
    0xe244,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 朗读 / 人声：Symbols `record_voice_over`（取代 Icons.record_voice_over_outlined / Icons.record_voice_over）
  static const IconData voice = IconData(
    0xe91f,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 在线发现：Symbols `travel_explore`（取代 Icons.travel_explore / Icons.travel_explore）
  static const IconData travelExplore = IconData(
    0xe2db,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 阅读 / 翻页：Symbols `auto_stories`（取代 Icons.auto_stories_outlined / Icons.auto_stories）
  static const IconData readingMode = IconData(
    0xe666,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 播放：Symbols `play_arrow`（取代 Icons.play_arrow_outlined / Icons.play_arrow）
  static const IconData play = IconData(
    0xe037,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 暂停：Symbols `pause`（取代 Icons.pause_outlined / Icons.pause）
  static const IconData pause = IconData(
    0xe034,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 播放（圆）：Symbols `play_circle`（取代 Icons.play_circle_outline / Icons.play_circle）
  static const IconData playCircle = IconData(
    0xe1c4,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 停止：Symbols `stop`（取代 Icons.stop / Icons.stop）
  static const IconData stop = IconData(
    0xe047,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 下一项：Symbols `skip_next`（取代 Icons.skip_next_outlined / Icons.skip_next）
  static const IconData skipNext = IconData(
    0xe044,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 上一项：Symbols `skip_previous`（取代 Icons.skip_previous_outlined / Icons.skip_previous）
  static const IconData skipPrevious = IconData(
    0xe045,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 快进：Symbols `fast_forward`（取代 Icons.fast_forward_outlined / Icons.fast_forward）
  static const IconData fastForward = IconData(
    0xe01f,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 快退：Symbols `fast_rewind`（取代 Icons.fast_rewind_outlined / Icons.fast_rewind）
  static const IconData fastRewind = IconData(
    0xe020,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 重播：Symbols `replay`（取代 Icons.replay / Icons.replay）
  static const IconData replay = IconData(
    0xe042,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 循环：Symbols `repeat`（取代 Icons.repeat / Icons.repeat）
  static const IconData repeat = IconData(
    0xe040,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 音量：Symbols `volume_up`（取代 Icons.volume_up_outlined / Icons.volume_up）
  static const IconData volumeUp = IconData(
    0xe050,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 静音：Symbols `volume_off`（取代 Icons.volume_off_outlined / Icons.volume_off）
  static const IconData volumeOff = IconData(
    0xe04f,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 音频 / 波形：Symbols `graphic_eq`（取代 Icons.graphic_eq / Icons.graphic_eq）
  static const IconData audio = IconData(
    0xe1b8,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 音乐：Symbols `music_note`（取代 Icons.music_note_outlined / Icons.music_note）
  static const IconData music = IconData(
    0xe405,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 麦克风：Symbols `mic`（取代 Icons.mic_none / Icons.mic）
  static const IconData mic = IconData(
    0xe31d,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 画中画：Symbols `picture_in_picture_alt`（取代 Icons.picture_in_picture_alt_outlined / Icons.picture_in_picture_alt）
  static const IconData pictureInPicture = IconData(
    0xe911,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 投屏：Symbols `cast`（取代 Icons.cast / Icons.cast）
  static const IconData cast = IconData(
    0xe307,
    fontFamily: kFushiSymbolsFontFamily,
  );

  /// 全部语义名 → 线框图标（测试 / 样张页遍历用）。
  static const Map<String, IconData> all = <String, IconData>{
    'home': home,
    'books': books,
    'manga': manga,
    'video': video,
    'browse': browse,
    'lookup': lookup,
    'games': games,
    'browserExtension': browserExtension,
    'settings': settings,
    'settingsGear': settingsGear,
    'audiobook': audiobook,
    'dictionary': dictionary,
    'subtitles': subtitles,
    'collection': collection,
    'tag': tag,
    'statistics': statistics,
    'ankiCard': ankiCard,
    'ocr': ocr,
    'lyrics': lyrics,
    'game': game,
    'tv': tv,
    'back': back,
    'forward': forward,
    'close': close,
    'more': more,
    'moreHoriz': moreHoriz,
    'menu': menu,
    'add': add,
    'addCircle': addCircle,
    'edit': edit,
    'rename': rename,
    'delete': delete,
    'deleteSweep': deleteSweep,
    'refresh': refresh,
    'restart': restart,
    'undo': undo,
    'redo': redo,
    'save': save,
    'search': search,
    'manageSearch': manageSearch,
    'filter': filter,
    'filterList': filterList,
    'sort': sort,
    'share': share,
    'openInNew': openInNew,
    'download': download,
    'upload': upload,
    'importFile': importFile,
    'sync': sync,
    'cloudSync': cloudSync,
    'copy': copy,
    'link': link,
    'linkOff': linkOff,
    'pin': pin,
    'bookmark': bookmark,
    'bookmarkAdd': bookmarkAdd,
    'favorite': favorite,
    'star': star,
    'history': history,
    'schedule': schedule,
    'calendar': calendar,
    'timer': timer,
    'speed': speed,
    'libraryAdd': libraryAdd,
    'dragHandle': dragHandle,
    'selectAll': selectAll,
    'checklist': checklist,
    'swap': swap,
    'zoomIn': zoomIn,
    'zoomOut': zoomOut,
    'fullscreen': fullscreen,
    'fullscreenExit': fullscreenExit,
    'gridView': gridView,
    'listView': listView,
    'visibility': visibility,
    'visibilityOff': visibilityOff,
    'lock': lock,
    'lockOpen': lockOpen,
    'chevronRight': chevronRight,
    'chevronLeft': chevronLeft,
    'expandMore': expandMore,
    'expandLess': expandLess,
    'dropDown': dropDown,
    'check': check,
    'success': success,
    'info': info,
    'warning': warning,
    'error': error,
    'help': help,
    'block': block,
    'pending': pending,
    'downloading': downloading,
    'downloadDone': downloadDone,
    'cloud': cloud,
    'cloudOff': cloudOff,
    'cloudDownload': cloudDownload,
    'cloudUpload': cloudUpload,
    'searchOff': searchOff,
    'brokenImage': brokenImage,
    'flag': flag,
    'verified': verified,
    'notifications': notifications,
    'appearance': appearance,
    'language': language,
    'globe': globe,
    'textFields': textFields,
    'fontSize': fontSize,
    'font': font,
    'keyboard': keyboard,
    'mouse': mouse,
    'touch': touch,
    'devices': devices,
    'server': server,
    'hub': hub,
    'wifi': wifi,
    'person': person,
    'account': account,
    'login': login,
    'logout': logout,
    'key': key,
    'shield': shield,
    'storage': storage,
    'backup': backup,
    'restoreBackup': restoreBackup,
    'folder': folder,
    'folderOpen': folderOpen,
    'file': file,
    'image': image,
    'imageSearch': imageSearch,
    'darkMode': darkMode,
    'lightMode': lightMode,
    'brightnessAuto': brightnessAuto,
    'ai': ai,
    'barChart': barChart,
    'widgets': widgets,
    'dashboardCustomize': dashboardCustomize,
    'quote': quote,
    'voice': voice,
    'travelExplore': travelExplore,
    'readingMode': readingMode,
    'play': play,
    'pause': pause,
    'playCircle': playCircle,
    'stop': stop,
    'skipNext': skipNext,
    'skipPrevious': skipPrevious,
    'fastForward': fastForward,
    'fastRewind': fastRewind,
    'replay': replay,
    'repeat': repeat,
    'volumeUp': volumeUp,
    'volumeOff': volumeOff,
    'audio': audio,
    'music': music,
    'mic': mic,
    'pictureInPicture': pictureInPicture,
    'cast': cast,
  };

  /// [icon] 的实心（FILL=1）版本：选中态 / 激活态用。非语义图标原样返回。
  static IconData filled(IconData icon) {
    if (icon.fontFamily != kFushiSymbolsFontFamily) return icon;
    return _filled[icon.codePoint] ?? icon;
  }

  /// [filled] 为 true 时取实心版，否则原样（导航项 / 开关按钮常用写法）。
  static IconData resolve(IconData icon, {required bool filled}) =>
      filled ? FushiIcons.filled(icon) : icon;

  static const Map<int, IconData> _filled = <int, IconData>{
    0xe01f: IconData(0xe01f, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe020: IconData(0xe020, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe034: IconData(0xe034, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe037: IconData(0xe037, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe03c: IconData(0xe03c, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe040: IconData(0xe040, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe042: IconData(0xe042, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe044: IconData(0xe044, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe045: IconData(0xe045, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe047: IconData(0xe047, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe048: IconData(0xe048, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe04f: IconData(0xe04f, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe050: IconData(0xe050, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe145: IconData(0xe145, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe14d: IconData(0xe14d, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe152: IconData(0xe152, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe15a: IconData(
      0xe15a,
      fontFamily: kFushiSymbolsFilledFontFamily,
      matchTextDirection: true,
    ),
    0xe161: IconData(0xe161, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe162: IconData(0xe162, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe164: IconData(
      0xe164,
      fontFamily: kFushiSymbolsFilledFontFamily,
      matchTextDirection: true,
    ),
    0xe166: IconData(
      0xe166,
      fontFamily: kFushiSymbolsFilledFontFamily,
      matchTextDirection: true,
    ),
    0xe167: IconData(0xe167, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe16c: IconData(0xe16c, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe16f: IconData(0xe16f, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe1a1: IconData(0xe1a1, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe1b8: IconData(0xe1b8, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe1bd: IconData(0xe1bd, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe1c4: IconData(0xe1c4, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe244: IconData(0xe244, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe245: IconData(0xe245, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe250: IconData(0xe250, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe25d: IconData(0xe25d, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe262: IconData(0xe262, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe26b: IconData(0xe26b, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe2c0: IconData(0xe2c0, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe2c1: IconData(0xe2c1, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe2c3: IconData(0xe2c3, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe2c7: IconData(0xe2c7, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe2c8: IconData(0xe2c8, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe2db: IconData(0xe2db, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe307: IconData(0xe307, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe312: IconData(0xe312, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe31d: IconData(0xe31d, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe323: IconData(0xe323, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe326: IconData(0xe326, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe338: IconData(0xe338, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe3ab: IconData(0xe3ab, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe3ad: IconData(0xe3ad, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe3f4: IconData(0xe3f4, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe404: IconData(0xe404, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe405: IconData(0xe405, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe40a: IconData(0xe40a, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe413: IconData(0xe413, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe41d: IconData(0xe41d, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe425: IconData(0xe425, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe429: IconData(0xe429, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe431: IconData(0xe431, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe43f: IconData(0xe43f, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe518: IconData(0xe518, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe51c: IconData(0xe51c, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe598: IconData(0xe598, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe5c4: IconData(
      0xe5c4,
      fontFamily: kFushiSymbolsFilledFontFamily,
      matchTextDirection: true,
    ),
    0xe5c5: IconData(0xe5c5, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe5c8: IconData(
      0xe5c8,
      fontFamily: kFushiSymbolsFilledFontFamily,
      matchTextDirection: true,
    ),
    0xe5cb: IconData(
      0xe5cb,
      fontFamily: kFushiSymbolsFilledFontFamily,
      matchTextDirection: true,
    ),
    0xe5cc: IconData(
      0xe5cc,
      fontFamily: kFushiSymbolsFilledFontFamily,
      matchTextDirection: true,
    ),
    0xe5cd: IconData(0xe5cd, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe5ce: IconData(0xe5ce, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe5cf: IconData(0xe5cf, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe5d0: IconData(0xe5d0, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe5d1: IconData(0xe5d1, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe5d2: IconData(0xe5d2, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe5d3: IconData(0xe5d3, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe5d4: IconData(0xe5d4, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe5d5: IconData(0xe5d5, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe5fa: IconData(0xe5fa, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe627: IconData(0xe627, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe63a: IconData(0xe63a, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe63e: IconData(0xe63e, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe65f: IconData(0xe65f, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe666: IconData(0xe666, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe668: IconData(0xe668, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe6b1: IconData(0xe6b1, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe73c: IconData(0xe73c, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe7f5: IconData(0xe7f5, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe80b: IconData(0xe80b, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe80d: IconData(0xe80d, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe864: IconData(0xe864, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe873: IconData(0xe873, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe875: IconData(0xe875, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe87a: IconData(0xe87a, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe87b: IconData(0xe87b, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe87e: IconData(0xe87e, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe88e: IconData(0xe88e, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe898: IconData(0xe898, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe899: IconData(0xe899, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe89e: IconData(
      0xe89e,
      fontFamily: kFushiSymbolsFilledFontFamily,
      matchTextDirection: true,
    ),
    0xe8b3: IconData(0xe8b3, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe8b8: IconData(0xe8b8, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe8ba: IconData(0xe8ba, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe8d4: IconData(0xe8d4, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe8e2: IconData(0xe8e2, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe8e7: IconData(0xe8e7, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe8ef: IconData(
      0xe8ef,
      fontFamily: kFushiSymbolsFilledFontFamily,
      matchTextDirection: true,
    ),
    0xe8f4: IconData(0xe8f4, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe8f5: IconData(0xe8f5, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe8fd: IconData(
      0xe8fd,
      fontFamily: kFushiSymbolsFilledFontFamily,
      matchTextDirection: true,
    ),
    0xe8ff: IconData(0xe8ff, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe900: IconData(0xe900, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe911: IconData(0xe911, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe913: IconData(0xe913, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe91f: IconData(0xe91f, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe92e: IconData(0xe92e, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe990: IconData(0xe990, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe99b: IconData(0xe99b, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe9a2: IconData(0xe9a2, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe9b0: IconData(0xe9b0, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe9b2: IconData(0xe9b2, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe9ba: IconData(0xe9ba, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe9e0: IconData(0xe9e0, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe9e4: IconData(0xe9e4, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe9f4: IconData(0xe9f4, fontFamily: kFushiSymbolsFilledFontFamily),
    0xe9fc: IconData(0xe9fc, fontFamily: kFushiSymbolsFilledFontFamily),
    0xea19: IconData(0xea19, fontFamily: kFushiSymbolsFilledFontFamily),
    0xea28: IconData(0xea28, fontFamily: kFushiSymbolsFilledFontFamily),
    0xea5b: IconData(0xea5b, fontFamily: kFushiSymbolsFilledFontFamily),
    0xea76: IconData(0xea76, fontFamily: kFushiSymbolsFilledFontFamily),
    0xea77: IconData(0xea77, fontFamily: kFushiSymbolsFilledFontFamily),
    0xeb5a: IconData(0xeb5a, fontFamily: kFushiSymbolsFilledFontFamily),
    0xebcc: IconData(0xebcc, fontFamily: kFushiSymbolsFilledFontFamily),
    0xec0b: IconData(0xec0b, fontFamily: kFushiSymbolsFilledFontFamily),
    0xef4f: IconData(0xef4f, fontFamily: kFushiSymbolsFilledFontFamily),
    0xef76: IconData(0xef76, fontFamily: kFushiSymbolsFilledFontFamily),
    0xef7a: IconData(0xef7a, fontFamily: kFushiSymbolsFilledFontFamily),
    0xefd6: IconData(0xefd6, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf001: IconData(0xf001, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf01f: IconData(0xf01f, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf02f: IconData(0xf02f, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf053: IconData(0xf053, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf05b: IconData(0xf05b, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf083: IconData(0xf083, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf08c: IconData(0xf08c, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf090: IconData(0xf090, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf091: IconData(0xf091, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf092: IconData(0xf092, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf097: IconData(0xf097, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf09a: IconData(0xf09a, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf09b: IconData(0xf09b, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf0be: IconData(0xf0be, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf0c6: IconData(0xf0c6, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf0d3: IconData(0xf0d3, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf10d: IconData(0xf10d, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf15c: IconData(0xf15c, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf20b: IconData(0xf20b, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf539: IconData(0xf539, fontFamily: kFushiSymbolsFilledFontFamily),
    0xf8b6: IconData(0xf8b6, fontFamily: kFushiSymbolsFilledFontFamily),
  };
}

/// 语义图标码位 → Apple 设计系统的 SF 风格字形（线框, 实心）。
const Map<int, (IconData, IconData)>
kFushiSymbolAppleMap = <int, (IconData, IconData)>{
  0xe01f: (CupertinoIcons.forward, CupertinoIcons.forward_fill),
  0xe020: (CupertinoIcons.backward, CupertinoIcons.backward_fill),
  0xe034: (CupertinoIcons.pause, CupertinoIcons.pause_fill),
  0xe037: (CupertinoIcons.play, CupertinoIcons.play_fill),
  0xe03c: (
    CupertinoIcons.plus_rectangle_on_rectangle,
    CupertinoIcons.plus_rectangle_on_rectangle,
  ),
  0xe040: (CupertinoIcons.repeat, CupertinoIcons.repeat),
  0xe042: (CupertinoIcons.gobackward, CupertinoIcons.gobackward),
  0xe044: (CupertinoIcons.forward_end, CupertinoIcons.forward_end_fill),
  0xe045: (CupertinoIcons.backward_end, CupertinoIcons.backward_end_fill),
  0xe047: (CupertinoIcons.stop_fill, CupertinoIcons.stop_fill),
  0xe048: (CupertinoIcons.captions_bubble, CupertinoIcons.captions_bubble_fill),
  0xe04f: (CupertinoIcons.speaker_slash, CupertinoIcons.speaker_slash_fill),
  0xe050: (CupertinoIcons.speaker_2, CupertinoIcons.speaker_2_fill),
  0xe145: (CupertinoIcons.add, CupertinoIcons.add),
  0xe14d: (CupertinoIcons.doc_on_doc, CupertinoIcons.doc_on_doc_fill),
  0xe152: (
    CupertinoIcons.line_horizontal_3_decrease,
    CupertinoIcons.line_horizontal_3_decrease,
  ),
  0xe15a: (CupertinoIcons.arrow_uturn_right, CupertinoIcons.arrow_uturn_right),
  0xe161: (CupertinoIcons.floppy_disk, CupertinoIcons.floppy_disk),
  0xe162: (
    CupertinoIcons.checkmark_square,
    CupertinoIcons.checkmark_square_fill,
  ),
  0xe164: (CupertinoIcons.sort_down, CupertinoIcons.sort_down),
  0xe166: (CupertinoIcons.arrow_uturn_left, CupertinoIcons.arrow_uturn_left),
  0xe167: (CupertinoIcons.textformat, CupertinoIcons.textformat),
  0xe16c: (CupertinoIcons.trash, CupertinoIcons.trash_fill),
  0xe16f: (CupertinoIcons.link, CupertinoIcons.link),
  0xe1a1: (CupertinoIcons.archivebox, CupertinoIcons.archivebox_fill),
  0xe1b8: (CupertinoIcons.waveform, CupertinoIcons.waveform),
  0xe1bd: (CupertinoIcons.square_grid_2x2, CupertinoIcons.square_grid_2x2_fill),
  0xe1c4: (CupertinoIcons.play_circle, CupertinoIcons.play_circle_fill),
  0xe244: (CupertinoIcons.quote_bubble_fill, CupertinoIcons.quote_bubble_fill),
  0xe245: (CupertinoIcons.textformat_size, CupertinoIcons.textformat_size),
  0xe250: (CupertinoIcons.link, CupertinoIcons.link),
  0xe25d: (CupertinoIcons.line_horizontal_3, CupertinoIcons.line_horizontal_3),
  0xe262: (CupertinoIcons.textformat, CupertinoIcons.textformat),
  0xe26b: (CupertinoIcons.chart_bar_fill, CupertinoIcons.chart_bar_fill),
  0xe2c0: (CupertinoIcons.cloud_download, CupertinoIcons.cloud_download_fill),
  0xe2c1: (CupertinoIcons.wifi_slash, CupertinoIcons.wifi_slash),
  0xe2c3: (CupertinoIcons.cloud_upload, CupertinoIcons.cloud_upload_fill),
  0xe2c7: (CupertinoIcons.folder, CupertinoIcons.folder_fill),
  0xe2c8: (CupertinoIcons.folder_open, CupertinoIcons.folder_open),
  0xe2db: (CupertinoIcons.globe, CupertinoIcons.globe),
  0xe307: (CupertinoIcons.tv, CupertinoIcons.tv),
  0xe312: (CupertinoIcons.keyboard, CupertinoIcons.keyboard),
  0xe31d: (CupertinoIcons.mic_fill, CupertinoIcons.mic_fill),
  0xe323: (CupertinoIcons.cursor_rays, CupertinoIcons.cursor_rays),
  0xe326: (CupertinoIcons.device_laptop, CupertinoIcons.device_laptop),
  0xe338: (CupertinoIcons.gamecontroller, CupertinoIcons.gamecontroller_fill),
  0xe3ab: (CupertinoIcons.sun_max, CupertinoIcons.sun_max_fill),
  0xe3ad: (CupertinoIcons.photo, CupertinoIcons.photo_fill),
  0xe3f4: (CupertinoIcons.photo, CupertinoIcons.photo_fill),
  0xe404: (CupertinoIcons.film, CupertinoIcons.film_fill),
  0xe405: (CupertinoIcons.music_note, CupertinoIcons.music_note),
  0xe40a: (CupertinoIcons.paintbrush, CupertinoIcons.paintbrush_fill),
  0xe413: (
    CupertinoIcons.photo_on_rectangle,
    CupertinoIcons.photo_fill_on_rectangle_fill,
  ),
  0xe41d: (CupertinoIcons.paintbrush, CupertinoIcons.paintbrush_fill),
  0xe425: (CupertinoIcons.timer, CupertinoIcons.timer_fill),
  0xe429: (
    CupertinoIcons.slider_horizontal_3,
    CupertinoIcons.slider_horizontal_3,
  ),
  0xe431: (CupertinoIcons.bookmark, CupertinoIcons.bookmark_fill),
  0xe43f: (CupertinoIcons.photo, CupertinoIcons.photo_fill),
  0xe518: (CupertinoIcons.sun_max, CupertinoIcons.sun_max_fill),
  0xe51c: (CupertinoIcons.moon, CupertinoIcons.moon_fill),
  0xe598: (CupertinoIcons.bookmark, CupertinoIcons.bookmark_fill),
  0xe5c4: (CupertinoIcons.chevron_back, CupertinoIcons.chevron_back),
  0xe5c5: (CupertinoIcons.chevron_down, CupertinoIcons.chevron_down),
  0xe5c8: (CupertinoIcons.chevron_forward, CupertinoIcons.chevron_forward),
  0xe5cb: (CupertinoIcons.chevron_left, CupertinoIcons.chevron_left),
  0xe5cc: (CupertinoIcons.chevron_right, CupertinoIcons.chevron_right),
  0xe5cd: (CupertinoIcons.xmark, CupertinoIcons.xmark),
  0xe5ce: (CupertinoIcons.chevron_up, CupertinoIcons.chevron_up),
  0xe5cf: (CupertinoIcons.chevron_down, CupertinoIcons.chevron_down),
  0xe5d0: (CupertinoIcons.fullscreen, CupertinoIcons.fullscreen),
  0xe5d1: (CupertinoIcons.fullscreen_exit, CupertinoIcons.fullscreen_exit),
  0xe5d2: (CupertinoIcons.line_horizontal_3, CupertinoIcons.line_horizontal_3),
  0xe5d3: (CupertinoIcons.ellipsis, CupertinoIcons.ellipsis),
  0xe5d4: (CupertinoIcons.ellipsis_vertical, CupertinoIcons.ellipsis_vertical),
  0xe5d5: (CupertinoIcons.arrow_clockwise, CupertinoIcons.arrow_clockwise),
  0xe5fa: (
    CupertinoIcons.doc_text_viewfinder,
    CupertinoIcons.doc_text_viewfinder,
  ),
  0xe627: (
    CupertinoIcons.arrow_2_circlepath,
    CupertinoIcons.arrow_2_circlepath,
  ),
  0xe63a: (CupertinoIcons.tv, CupertinoIcons.tv_fill),
  0xe63e: (CupertinoIcons.wifi, CupertinoIcons.wifi),
  0xe65f: (CupertinoIcons.sparkles, CupertinoIcons.sparkles),
  0xe666: (CupertinoIcons.book, CupertinoIcons.book_fill),
  0xe668: (CupertinoIcons.checkmark, CupertinoIcons.checkmark),
  0xe6b1: (CupertinoIcons.checkmark_square, CupertinoIcons.checkmark_square),
  0xe73c: (CupertinoIcons.lock, CupertinoIcons.lock),
  0xe7f5: (CupertinoIcons.bell, CupertinoIcons.bell_fill),
  0xe80b: (CupertinoIcons.globe, CupertinoIcons.globe),
  0xe80d: (CupertinoIcons.share, CupertinoIcons.share),
  0xe864: (CupertinoIcons.cloud_upload, CupertinoIcons.cloud_upload_fill),
  0xe873: (CupertinoIcons.doc_text, CupertinoIcons.doc_text_fill),
  0xe875: (
    CupertinoIcons.rectangle_grid_1x2,
    CupertinoIcons.rectangle_grid_1x2_fill,
  ),
  0xe87a: (CupertinoIcons.compass, CupertinoIcons.compass_fill),
  0xe87b: (CupertinoIcons.cube_box, CupertinoIcons.cube_box_fill),
  0xe87e: (CupertinoIcons.heart, CupertinoIcons.heart_fill),
  0xe88e: (CupertinoIcons.info_circle, CupertinoIcons.info_circle_fill),
  0xe898: (CupertinoIcons.lock_open, CupertinoIcons.lock_open_fill),
  0xe899: (CupertinoIcons.lock, CupertinoIcons.lock_fill),
  0xe89e: (
    CupertinoIcons.arrow_up_right_square,
    CupertinoIcons.arrow_up_right_square,
  ),
  0xe8b3: (CupertinoIcons.clock, CupertinoIcons.clock),
  0xe8b8: (CupertinoIcons.gear, CupertinoIcons.gear_solid),
  0xe8ba: (
    CupertinoIcons.arrow_counterclockwise,
    CupertinoIcons.arrow_counterclockwise,
  ),
  0xe8d4: (
    CupertinoIcons.arrow_right_arrow_left,
    CupertinoIcons.arrow_right_arrow_left,
  ),
  0xe8e2: (CupertinoIcons.globe, CupertinoIcons.globe),
  0xe8e7: (CupertinoIcons.bookmark, CupertinoIcons.bookmark_fill),
  0xe8ef: (CupertinoIcons.list_bullet, CupertinoIcons.list_bullet),
  0xe8f4: (CupertinoIcons.eye, CupertinoIcons.eye_fill),
  0xe8f5: (CupertinoIcons.eye_slash, CupertinoIcons.eye_slash_fill),
  0xe8fd: (CupertinoIcons.question_circle, CupertinoIcons.question_circle),
  0xe8ff: (CupertinoIcons.zoom_in, CupertinoIcons.zoom_in),
  0xe900: (CupertinoIcons.zoom_out, CupertinoIcons.zoom_out),
  0xe911: (
    CupertinoIcons.rectangle_on_rectangle,
    CupertinoIcons.rectangle_on_rectangle,
  ),
  0xe913: (
    CupertinoIcons.hand_point_right,
    CupertinoIcons.hand_point_right_fill,
  ),
  0xe91f: (CupertinoIcons.waveform, CupertinoIcons.waveform),
  0xe92e: (CupertinoIcons.trash, CupertinoIcons.trash_fill),
  0xe990: (CupertinoIcons.plus_circle, CupertinoIcons.plus_circle_fill),
  0xe99b: (CupertinoIcons.square_grid_2x2, CupertinoIcons.square_grid_2x2_fill),
  0xe9a2: (CupertinoIcons.square_pencil, CupertinoIcons.square_pencil),
  0xe9b0: (CupertinoIcons.square_grid_2x2, CupertinoIcons.square_grid_2x2_fill),
  0xe9b2: (CupertinoIcons.house, CupertinoIcons.house_fill),
  0xe9ba: (
    CupertinoIcons.square_arrow_right,
    CupertinoIcons.square_arrow_right,
  ),
  0xe9e0: (CupertinoIcons.shield, CupertinoIcons.shield_fill),
  0xe9e4: (CupertinoIcons.speedometer, CupertinoIcons.speedometer),
  0xe9f4: (CupertinoIcons.circle_grid_hex, CupertinoIcons.circle_grid_hex_fill),
  0xe9fc: (CupertinoIcons.arrow_up_doc, CupertinoIcons.arrow_up_doc_fill),
  0xea19: (CupertinoIcons.book, CupertinoIcons.book_fill),
  0xea28: (CupertinoIcons.gamecontroller, CupertinoIcons.gamecontroller_fill),
  0xea5b: (CupertinoIcons.hourglass, CupertinoIcons.hourglass),
  0xea76: (CupertinoIcons.search, CupertinoIcons.search),
  0xea77: (
    CupertinoIcons.arrow_right_to_line,
    CupertinoIcons.arrow_right_to_line,
  ),
  0xeb5a: (
    CupertinoIcons.arrow_2_circlepath,
    CupertinoIcons.arrow_2_circlepath,
  ),
  0xebcc: (CupertinoIcons.calendar, CupertinoIcons.calendar),
  0xec0b: (CupertinoIcons.music_note_list, CupertinoIcons.music_note_list),
  0xef4f: (
    CupertinoIcons.line_horizontal_3_decrease_circle_fill,
    CupertinoIcons.line_horizontal_3_decrease_circle_fill,
  ),
  0xef76: (CupertinoIcons.checkmark_seal, CupertinoIcons.checkmark_seal_fill),
  0xef7a: (CupertinoIcons.search, CupertinoIcons.search),
  0xefd6: (CupertinoIcons.clock_fill, CupertinoIcons.clock_fill),
  0xf001: (
    CupertinoIcons.arrow_down_circle_fill,
    CupertinoIcons.arrow_down_circle_fill,
  ),
  0xf01f: (CupertinoIcons.headphones, CupertinoIcons.headphones),
  0xf02f: (CupertinoIcons.doc_text_search, CupertinoIcons.doc_text_search),
  0xf053: (
    CupertinoIcons.arrow_counterclockwise,
    CupertinoIcons.arrow_counterclockwise,
  ),
  0xf05b: (CupertinoIcons.tag, CupertinoIcons.tag_fill),
  0xf083: (
    CupertinoIcons.exclamationmark_triangle,
    CupertinoIcons.exclamationmark_triangle_fill,
  ),
  0xf08c: (CupertinoIcons.nosign, CupertinoIcons.nosign),
  0xf090: (
    CupertinoIcons.arrow_down_circle,
    CupertinoIcons.arrow_down_circle_fill,
  ),
  0xf091: (
    CupertinoIcons.checkmark_circle_fill,
    CupertinoIcons.checkmark_circle_fill,
  ),
  0xf092: (CupertinoIcons.chart_bar, CupertinoIcons.chart_bar_fill),
  0xf097: (CupertinoIcons.pencil, CupertinoIcons.pencil),
  0xf09a: (CupertinoIcons.star, CupertinoIcons.star_fill),
  0xf09b: (CupertinoIcons.arrow_up_circle, CupertinoIcons.arrow_up_circle_fill),
  0xf0be: (
    CupertinoIcons.checkmark_circle,
    CupertinoIcons.checkmark_circle_fill,
  ),
  0xf0c6: (CupertinoIcons.flag, CupertinoIcons.flag_fill),
  0xf0d3: (CupertinoIcons.person, CupertinoIcons.person_fill),
  0xf10d: (CupertinoIcons.pin, CupertinoIcons.pin_fill),
  0xf15c: (CupertinoIcons.cloud, CupertinoIcons.cloud_fill),
  0xf20b: (
    CupertinoIcons.person_crop_circle,
    CupertinoIcons.person_crop_circle_fill,
  ),
  0xf539: (CupertinoIcons.book, CupertinoIcons.book_fill),
  0xf8b6: (
    CupertinoIcons.exclamationmark_circle,
    CupertinoIcons.exclamationmark_circle_fill,
  ),
};
